### PR TITLE
[WIP] trying to get img2img similarly optimized

### PR DESCRIPTION
**Pull request by sawolf**
disclaimer - it looks like I threw away your most recent commit when I tried to merge it in. I'll commit to fixing that if/when the actual img2img code is working properly.

Currently the optimized_img2img.py code both:
 - fits on an RTX 2070 GPU (sometimes)
 - produces some kind of output

However, it looks like the script is overlaying the noise on the original image, and either a) doing a very small amount of work compared to what's required, or b) not doing anything at all (i.e. not feeding the work from the previous iteration into the next iteration)

If I run the actual example prompt:
````python scripts/img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img inputs/sketch-mountains-input.jpg --strength 0.8````
I get an out of memory error.
If I scale the image down to 512x256 (saving to sketch-mountains-input2.jpg) and try again:
```python .\optimizedSD\optimized_img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img .\inputs\sketch-mountains-input2.jpg --strength 0.8```
My setup runs for about 2 minutes (40 timesteps) and produces these two images:

If I reduce strength to 0.2:
```python .\optimizedSD\optimized_img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img .\inputs\sketch-mountains-input2.jpg --strength 0.2```
My setup runs for 10 timesteps or ~30 seconds and produces these

Maybe this is wishful thinking, but it does look like it's doing a little bit - e.g. the tree(s) just to the right of the river look slightly closer to the cluster of trees in the CompVis repo's original example run.

Haven't used pytorch before this so I'm not really sure where to go from here as far as debugging - any thoughts are welcome.

### CODE REVIEW

**Comment by andreae293** [comment]
not sure if this can help you but using the script txt2img_gradio.py from this branch
https://github.com/harubaru/waifu-diffusion
im able to use the img2img on my 3060ti

not sure which kind of optimization he used

**Comment by sawolf** [comment]
That script works great for me - thanks for the tip.

**Comment by andreae293** [comment]
Did you get how it was optimized? im curious now

**Comment by AndreThompson-Atlow** [comment]
Does that mean the txt2img_gradio.py script from waifu-diffusion is actually an img2img script? Or did you have to integrate it into the img2img script somehow?

**Comment by andreae293** [comment]
txt2img_gradio.py offers the web interface and other things
to generate the img, txt2img_gradio.py uses pretty much the same code from img2img.py but adds the aforementioned lines to use less vram

**Pull request closed without merging**
